### ISSUE TITLE
[Feature] Redirect /blog/feed

### ISSUE THREAD

**Issue by carbontwelve** [photogabble/website#244]
Highlighted by #243 is the need to move /blog/feed.xml to /writing/feed.xml but also to add atom feeds for all content types.

**Comment by MaNemoj01** [comment]
Hello @carbontwelve, just out of curiosity I wanted to make my first commit to something outside of my 9to5 work haha but can't really push the code because of restriction.

I've cloned the repo with SSH but when I want to push this pops up :D

<img width="719" alt="image" src="https://user-images.githubusercontent.com/44163914/220314862-4f3f6e54-e4f1-4945-94b6-082c13f6afe8.png">

**Comment by carbontwelve** [comment]
@MaNemoj01 thats cool. With GitHub you first "fork" the project and then you can raise a PR against the upstream: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by MaNemoj01** [comment]
Oh, gotcha forgot that part :D Thank you @carbontwelve.
